export const CODEX_COMPOSER_RADIUS = 24;
export const CODEX_COMPOSER_SUPERELLIPSE_RADIUS = 30;
export const CODEX_COMPOSER_MIN_HEIGHT = 72;
export const CODEX_COMPOSER_HORIZONTAL_PADDING = 12;
export const CODEX_COMPOSER_TOP_PADDING = 10;
export const CODEX_COMPOSER_BOTTOM_PADDING = 8;
export const CODEX_COMPOSER_HIGHLIGHT = "inset 0 1px 0 rgba(255, 255, 255, 0.1)";
