import type { Descendant } from "slate";
import type { SessionConfigState, SessionConfigAction } from "../sessionConfig/types";

// ─── SDK message shape helpers ───────────────────────────────────────────────
// We do not import the full Zod schemas here to keep the renderer bundle lean.
// Instead, we type-narrow on `type` + `subtype` discriminants at runtime.

export type SdkMessageType =
	| "assistant"
	| "user"
	| "stream_event"
	| "result"
	| "system"
	| "tool_progress"
	| "tool_use_summary"
	| "rate_limit_event"
	| "auth_status"
	| "prompt_suggestion";

export type RawSdkMessage = Record<string, unknown> & { type: SdkMessageType };

// ─── Timeline item types ─────────────────────────────────────────────────────

export type SpinnerMode =
	| "requesting"
	| "thinking"
	| "tool-input"
	| "tool-use"
	| "responding"
	| null;

export type VendorStatusSource = "vendor" | "fallback" | null;

export type ToolStatus =
	| "streaming-input"
	| "executing"
	| "awaiting-permission"
	| "completed"
	| "failed";

export type StreamingToolUse = {
	toolUseId: string;
	toolName: string;
	inputSummary: string;
	rawInput: Record<string, unknown>;
	status: ToolStatus;
	resultSummary?: string;
	/** Elapsed seconds from tool_progress heartbeats */
	elapsedSeconds?: number;
};

export type ThinkingBlockData = {
	text: string;
	isStreaming: boolean;
	isRedacted: boolean;
};

export type DiffFile = {
	filePath: string;
	additions: number;
	deletions: number;
	/** Unified diff patch string generated by the `diff` package */
	patch: string;
};

export type CodeAgentUserImagePreview = {
	preview: string | null;
	fileName: string;
};

export type CodeAgentUserPathTag = {
	absolutePath: string;
	name: string;
	isDirectory: boolean;
};

export type CodeAgentUserMentionTag = {
	kind: string;
	label: string;
	icon?: string;
};

export type CodeAgentUserMessageMeta = {
	imagePreviews?: CodeAgentUserImagePreview[];
	mentionTags?: CodeAgentUserMentionTag[];
	pathTags?: CodeAgentUserPathTag[];
	richContent?: Descendant[];
};

/** Items that form the visual timeline in CodeTimeline */
export type CodeAgentTimelineItem =
	| { kind: "init"; id: string; model: string; permissionMode: string; toolCount: number; mcpCount: number; cwd: string }
	| { kind: "thinking"; id: string; data: ThinkingBlockData }
	| { kind: "assistant-text"; id: string; text: string; isStreaming: boolean; createdAt?: number }
	| { kind: "assistant-usage"; id: string; usage: { inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWriteTokens: number; totalTokens: number }; model?: string; costUsd?: number; durationMs?: number; ttftMs?: number; tps?: number }
	| { kind: "tool-use"; id: string; tool: StreamingToolUse }
	| { kind: "diff"; id: string; files: DiffFile[] }
	| {
		kind: "user";
		id: string;
		text: string;
		createdAt?: number;
		imagePreviews?: CodeAgentUserImagePreview[];
		mentionTags?: CodeAgentUserMentionTag[];
		pathTags?: CodeAgentUserPathTag[];
		richContent?: Descendant[];
	}
	| { kind: "system-notice"; id: string; text: string; variant?: "info" | "warning" | "error" }
	| { kind: "compact-boundary"; id: string; preTokens: number; trigger: string }
	| { kind: "rate-limit"; id: string; resetsAt: number | null; utilization: number | null; status: string }
	| { kind: "api-retry"; id: string; attempt: number; maxRetries: number; delayMs: number; error: string }
	| { kind: "hook"; id: string; hookName: string; hookEvent: string; outcome: "started" | "progress" | "success" | "error"; stdout?: string; exitCode?: number | null }
	| { kind: "task-start"; id: string; taskId: string; description: string; parentTaskId?: string }
	| { kind: "task-end"; id: string; taskId: string; status: "completed" | "failed" | "stopped"; summary: string; durationMs?: number }
	| { kind: "result"; id: string; isError: boolean; numTurns: number; totalCostUsd: number; durationMs: number }
	| { kind: "permission-request"; id: string; requestId: string; toolName: string; rawInput: Record<string, unknown>; title?: string; description?: string }
	| { kind: "elicitation"; id: string; elicitationId: string; mcpServerName: string; message: string; requestedSchema: Record<string, unknown> | null };

// ─── Session init info ────────────────────────────────────────────────────────
export type SessionInitInfo = {
	model: string;
	permissionMode: string;
	tools: string[];
	mcpServers: Array<{ name: string; status: string }>;
	cwd: string;
	claudeCodeVersion: string;
};

// ─── Elicitation request ─────────────────────────────────────────────────────
export type PendingElicitation = {
	elicitationId: string;
	mcpServerName: string;
	message: string;
	requestedSchema: Record<string, unknown> | null;
	mode?: string;
};

// ─── Permission request ───────────────────────────────────────────────────────
export type PendingPermission = {
	requestId: string;
	toolName: string;
	rawInput: Record<string, unknown>;
	inputSummary: string;
	title?: string;
	description?: string;
};

// ─── Active subagent task ─────────────────────────────────────────────────────
export type SubagentStatus = "running" | "completed" | "failed" | "stopped";

export type SubagentProgressEntry = {
	text: string;
	timestamp: number;
};

export type ActiveTask = {
	taskId: string;
	description: string;
	toolUseId?: string;
	parentTaskId?: string;
	status: SubagentStatus;
	progressEntries: SubagentProgressEntry[];
	toolNames: string[];
	startedAt: number;
	completedAt?: number;
	summary?: string;
};

// ─── Rate-limit state ─────────────────────────────────────────────────────────
export type RateLimitInfo = {
	status: string;
	resetsAt?: number;
	utilization?: number;
};

export type CodeAgentContextWindowUsage = {
	contextWindowSize: number;
	windowSource: "reported" | "estimated";
	model: string | null;
	inputTokens: number;
	outputTokens: number;
	cacheReadInputTokens: number;
	cacheCreationInputTokens: number;
	usedTokens: number;
	remainingTokens: number;
	usedPercentage: number;
	remainingPercentage: number;
	updatedAt: number;
	sourceMessageId?: string | null;
};

// ─── Timeline slice state & action ──────────────────────────────────────────

export interface TimelineState {
	sessionId: string | null;
	sessionInit: SessionInitInfo | null;
	sessionState: "idle" | "running" | "requires_action";
	sessionTitle: string | null;
	lastUpdatedAt: number | null;
	items: CodeAgentTimelineItem[];
	streaming: {
		thinkingText: string;
		isThinking: boolean;
		assistantText: string;
		isStreaming: boolean;
		spinnerMode: SpinnerMode;
		vendorStatusText: string;
		vendorStatusSource: VendorStatusSource;
		toolUses: Map<string, StreamingToolUse>;
		accumulatedUsage: { inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWriteTokens: number } | null;
		turnStartedAt: number;
		firstTokenAt: number;
	};
	pendingPermission: PendingPermission | null;
	pendingElicitation: PendingElicitation | null;
	activeTasks: Map<string, ActiveTask>;
	rateLimitInfo: RateLimitInfo | null;
	contextUsage: CodeAgentContextWindowUsage | null;
	perfTurnStartedAt: number;
	perfFirstTokenAt: number;
	sessionAllowedTools: Set<string>;
}

export interface TimelineStoreAction {
	pushSdkMessage: (raw: unknown) => void;
	pushUserMessage: (text: string, meta?: CodeAgentUserMessageMeta) => void;
	setContextUsage: (usage: CodeAgentContextWindowUsage | null) => void;
	appendStreamingText: (text: string) => void;
	setPendingPermission: (p: PendingPermission | null) => void;
	resolvePermission: (requestId: string, _decision: "allow" | "allow-session" | "deny") => void;
	resolveElicitation: (action: "accept" | "decline", content?: Record<string, unknown>) => void;
	addSessionAllowedTool: (toolName: string) => void;
	reset: () => void;
	resetStreaming: () => void;
}

// ─── Composed store ─────────────────────────────────────────────────────────

export interface ChatStoreAction extends TimelineStoreAction, SessionConfigAction {}

export type CodeAgentStore = TimelineState & SessionConfigState & ChatStoreAction;
