/**
 * Zustand store for Claude Code CLI agent state.
 *
 * Receives raw SDK messages from `code-agent:sdk-message` IPC events and
 * transforms them into structured UI state consumed by MiniChat components.
 */
import { create } from "zustand";

// ─── SDK message shape helpers ───────────────────────────────────────────────
// We do not import the full Zod schemas here to keep the renderer bundle lean.
// Instead, we type-narrow on `type` + `subtype` discriminants at runtime.

export type SdkMessageType =
	| "assistant"
	| "user"
	| "stream_event"
	| "result"
	| "system"
	| "tool_progress"
	| "tool_use_summary"
	| "rate_limit_event"
	| "auth_status"
	| "prompt_suggestion";

export type RawSdkMessage = Record<string, unknown> & { type: SdkMessageType };

// ─── Timeline item types ─────────────────────────────────────────────────────

export type SpinnerMode =
	| "requesting"
	| "thinking"
	| "tool-input"
	| "tool-use"
	| "responding"
	| null;

export type ToolStatus =
	| "streaming-input"
	| "executing"
	| "awaiting-permission"
	| "completed"
	| "failed";

export type StreamingToolUse = {
	toolUseId: string;
	toolName: string;
	inputSummary: string;
	rawInput: Record<string, unknown>;
	status: ToolStatus;
	resultSummary?: string;
	/** Elapsed seconds from tool_progress heartbeats */
	elapsedSeconds?: number;
};

export type ThinkingBlockData = {
	text: string;
	isStreaming: boolean;
	isRedacted: boolean;
};

export type DiffFile = {
	filePath: string;
	additions: number;
	deletions: number;
	/** Unified diff patch string generated by the `diff` package */
	patch: string;
};

/** Items that form the visual timeline in CodeTimeline */
export type CodeAgentTimelineItem =
	| { kind: "init"; id: string; model: string; permissionMode: string; toolCount: number; mcpCount: number; cwd: string }
	| { kind: "thinking"; id: string; data: ThinkingBlockData }
	| { kind: "assistant-text"; id: string; text: string; isStreaming: boolean }
	| { kind: "tool-use"; id: string; tool: StreamingToolUse }
	| { kind: "diff"; id: string; files: DiffFile[] }
	| { kind: "user"; id: string; text: string }
	| { kind: "system-notice"; id: string; text: string; variant?: "info" | "warning" | "error" }
	| { kind: "compact-boundary"; id: string; preTokens: number; trigger: string }
	| { kind: "rate-limit"; id: string; resetsAt: number | null; utilization: number | null; status: string }
	| { kind: "api-retry"; id: string; attempt: number; maxRetries: number; delayMs: number; error: string }
	| { kind: "hook"; id: string; hookName: string; hookEvent: string; outcome: "started" | "progress" | "success" | "error"; stdout?: string; exitCode?: number | null }
	| { kind: "task-start"; id: string; taskId: string; description: string }
	| { kind: "task-end"; id: string; taskId: string; status: "completed" | "failed" | "stopped"; summary: string }
	| { kind: "result"; id: string; isError: boolean; numTurns: number; totalCostUsd: number; durationMs: number }
	| { kind: "permission-request"; id: string; requestId: string; toolName: string; rawInput: Record<string, unknown>; title?: string; description?: string }
	| { kind: "elicitation"; id: string; elicitationId: string; mcpServerName: string; message: string; requestedSchema: Record<string, unknown> | null };

// ─── Session init info ────────────────────────────────────────────────────────
export type SessionInitInfo = {
	model: string;
	permissionMode: string;
	tools: string[];
	mcpServers: Array<{ name: string; status: string }>;
	cwd: string;
	claudeCodeVersion: string;
};

// ─── Elicitation request ─────────────────────────────────────────────────────
export type PendingElicitation = {
	elicitationId: string;
	mcpServerName: string;
	message: string;
	requestedSchema: Record<string, unknown> | null;
	mode?: string;
};

// ─── Permission request ───────────────────────────────────────────────────────
export type PendingPermission = {
	requestId: string;
	toolName: string;
	rawInput: Record<string, unknown>;
	inputSummary: string;
	title?: string;
	description?: string;
};

// ─── Active subagent task ─────────────────────────────────────────────────────
export type ActiveTask = {
	taskId: string;
	description: string;
	toolUseId?: string;
};

// ─── Rate-limit state ─────────────────────────────────────────────────────────
export type RateLimitInfo = {
	status: string;
	resetsAt?: number;
	utilization?: number;
};

// ─── Store interface ──────────────────────────────────────────────────────────
export interface CodeAgentStore {
	// Session metadata
	sessionId: string | null;
	sessionInit: SessionInitInfo | null;
	sessionState: "idle" | "running" | "requires_action";
	/** Title derived from the first user message in this session (first 20 chars) */
	sessionTitle: string | null;
	/** Timestamp (ms) of when the last result message was received */
	lastUpdatedAt: number | null;

	// Full message timeline
	items: CodeAgentTimelineItem[];

	// Current turn streaming state
	streaming: {
		thinkingText: string;
		isThinking: boolean;
		assistantText: string;
		isStreaming: boolean;
		spinnerMode: SpinnerMode;
		/** Active tool uses keyed by tool_use_id */
		toolUses: Map<string, StreamingToolUse>;
	};

	// Pending user interactions
	pendingPermission: PendingPermission | null;
	pendingElicitation: PendingElicitation | null;

	// Subagent tasks currently running
	activeTasks: Map<string, ActiveTask>;

	// Rate limit state
	rateLimitInfo: RateLimitInfo | null;

	// Actions
	pushSdkMessage: (raw: unknown) => void;
	/** Append incremental text from `code-agent:token` IPC events for live streaming */
	appendStreamingText: (text: string) => void;
	setPendingPermission: (p: PendingPermission | null) => void;
	resolvePermission: (requestId: string, _decision: "allow" | "deny") => void;
	resolveElicitation: (action: "accept" | "decline", content?: Record<string, unknown>) => void;
	reset: () => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uid() {
	return crypto.randomUUID();
}

function extractTextContent(value: unknown): string {
	if (!value) return "";
	if (typeof value === "string") return value;
	if (Array.isArray(value)) {
		return value
			.map((item) => {
				if (typeof item === "string") return item;
				if (item && typeof (item as Record<string, unknown>).text === "string")
					return (item as Record<string, unknown>).text as string;
				return "";
			})
			.filter(Boolean)
			.join("\n");
	}
	if (typeof value === "object") {
		const obj = value as Record<string, unknown>;
		if (typeof obj.text === "string") return obj.text;
	}
	return "";
}

/** Build a short display summary for a tool's input parameters */
export function buildInputSummary(toolName: string, input: Record<string, unknown>): string {
	if (!input) return "";
	const name = toolName.toLowerCase();
	const truncate = (s: string, max = 80) =>
		s.length > max ? `${s.slice(0, max)}…` : s;

	const str = (v: unknown) => (typeof v === "string" ? v : "");

	if (["read", "write", "edit", "multiedit", "notebookedit"].includes(name)) {
		return truncate(str(input.file_path) || str(input.path));
	}
	if (name === "bash") return truncate(str(input.command), 72);
	if (name === "grep") {
		const pat = str(input.pattern);
		const path = str(input.path);
		return pat ? truncate(path ? `"${pat}" in ${path}` : `"${pat}"`) : "";
	}
	if (name === "glob") {
		const glob = str(input.pattern) || str(input.glob_pattern);
		const dir = str(input.path) || str(input.target_directory);
		return truncate(dir ? `${glob} in ${dir}` : glob);
	}
	if (name === "webfetch") return truncate(str(input.url));
	if (name === "agent" || name === "task") return truncate(str(input.description) || str(input.prompt), 60);
	const first = Object.values(input).find((v) => typeof v === "string" && (v as string).length > 0);
	return first ? truncate(first as string) : "";
}

/** Generate unified diff patch string between two text buffers */
function buildUnifiedPatch(
	filePath: string,
	oldContent: string,
	newContent: string,
): { patch: string; additions: number; deletions: number } {
	const oldLines = oldContent.split("\n");
	const newLines = newContent.split("\n");
	let additions = 0;
	let deletions = 0;

	// Simple line-diff to produce unified output
	// In practice the `diff` npm package should be used for robust output;
	// this is a lightweight fallback so no extra dependency is required at
	// compile time in the renderer. The DiffView component can also use
	// the `diff` package directly if available.
	const lines: string[] = [`--- a/${filePath}`, `+++ b/${filePath}`];
	const maxLen = Math.max(oldLines.length, newLines.length);
	for (let i = 0; i < maxLen; i++) {
		if (i < oldLines.length && i < newLines.length) {
			if (oldLines[i] !== newLines[i]) {
				lines.push(`-${oldLines[i]}`);
				lines.push(`+${newLines[i]}`);
				deletions++;
				additions++;
			} else {
				lines.push(` ${oldLines[i]}`);
			}
		} else if (i < newLines.length) {
			lines.push(`+${newLines[i]}`);
			additions++;
		} else {
			lines.push(`-${oldLines[i]}`);
			deletions++;
		}
	}

	return { patch: lines.join("\n"), additions, deletions };
}

/** Extract and add a diff item for file-edit/write tool uses */
function buildDiffForToolUse(
	tu: StreamingToolUse,
	addItem: (item: CodeAgentTimelineItem) => void,
) {
	const name = tu.toolName.toLowerCase();
	const isFileEdit = ["edit", "fileedit", "strreplacebasededitattempt", "multiedit", "write", "filewrite"].includes(name);
	if (!isFileEdit || !tu.rawInput) return;
	const filePath = String(tu.rawInput.file_path || tu.rawInput.path || "");
	const oldContent = String(tu.rawInput.old_content || tu.rawInput.old_string || "");
	const newContent = String(tu.rawInput.new_content || tu.rawInput.new_string || tu.rawInput.content || "");
	if (!filePath || !(oldContent || newContent)) return;
	const { patch, additions, deletions } = buildUnifiedPatch(filePath, oldContent, newContent);
	if (additions + deletions > 0) {
		addItem({ kind: "diff", id: uid(), files: [{ filePath, additions, deletions, patch }] });
	}
}

// ─── Initial state factory ────────────────────────────────────────────────────
function initialStreaming() {
	return {
		thinkingText: "",
		isThinking: false,
		assistantText: "",
		isStreaming: false,
		spinnerMode: null as SpinnerMode,
		toolUses: new Map<string, StreamingToolUse>(),
	};
}

// ─── Store ────────────────────────────────────────────────────────────────────
export const useCodeAgentStore = create<CodeAgentStore>((set, get) => ({
	sessionId: null,
	sessionInit: null,
	sessionState: "idle",
	sessionTitle: null,
	lastUpdatedAt: null,
	items: [],
	streaming: initialStreaming(),
	pendingPermission: null,
	pendingElicitation: null,
	activeTasks: new Map(),
	rateLimitInfo: null,

	reset: () => {
		set({
			sessionId: null,
			sessionInit: null,
			sessionState: "idle",
			sessionTitle: null,
			lastUpdatedAt: null,
			items: [],
			streaming: initialStreaming(),
			pendingPermission: null,
			pendingElicitation: null,
			activeTasks: new Map(),
			rateLimitInfo: null,
		});
	},

	appendStreamingText: (text) => {
		set((state) => ({
			streaming: {
				...state.streaming,
				assistantText: state.streaming.assistantText + text,
				isStreaming: true,
				spinnerMode: "responding",
			},
		}));
	},

	setPendingPermission: (p) => {
		set({ pendingPermission: p });
	},

	resolvePermission: (requestId, _decision) => {
		const current = get().pendingPermission;
		if (current?.requestId === requestId) {
			set({ pendingPermission: null });
		}
		// Remove any pending permission item from timeline so the card disappears
		set((state) => ({
			items: state.items.filter(
				(item) =>
					!(item.kind === "permission-request" && item.requestId === requestId),
			),
		}));
	},

	resolveElicitation: (_action, _content) => {
		set({ pendingElicitation: null });
		set((state) => ({
			items: state.items.filter((item) => item.kind !== "elicitation"),
		}));
	},

	pushSdkMessage: (raw) => {
		if (!raw || typeof raw !== "object") return;
		const msg = raw as Record<string, unknown>;
		const type = msg.type as string | undefined;
		if (!type) return;

		const addItem = (item: CodeAgentTimelineItem) => {
			set((state) => ({ items: [...state.items, item] }));
		};

		// ── system messages ────────────────────────────────────────────────────
		if (type === "system") {
			const subtype = msg.subtype as string | undefined;

			if (subtype === "init") {
				const tools = Array.isArray(msg.tools) ? (msg.tools as string[]) : [];
				const mcpServers = Array.isArray(msg.mcp_servers)
					? (msg.mcp_servers as Array<{ name: string; status: string }>)
					: [];
				const init: SessionInitInfo = {
					model: String(msg.model || ""),
					permissionMode: String(msg.permissionMode || "default"),
					tools,
					mcpServers,
					cwd: String(msg.cwd || ""),
					claudeCodeVersion: String(msg.claude_code_version || ""),
				};
				set({
					sessionId: String(msg.session_id || ""),
					sessionInit: init,
				});
				addItem({
					kind: "init",
					id: uid(),
					model: init.model,
					permissionMode: init.permissionMode,
					toolCount: tools.length,
					mcpCount: mcpServers.length,
					cwd: init.cwd,
				});
				return;
			}

			if (subtype === "compact_boundary") {
				const meta = msg.compact_metadata as Record<string, unknown> | undefined;
				addItem({
					kind: "compact-boundary",
					id: uid(),
					preTokens: Number(meta?.pre_tokens ?? 0),
					trigger: String(meta?.trigger ?? "auto"),
				});
				return;
			}

			if (subtype === "status") {
				const s = msg.status;
				if (s === "compacting") {
					addItem({ kind: "system-notice", id: uid(), text: "⟳ 正在压缩上下文…", variant: "info" });
				}
				set({ sessionState: s === null ? "idle" : "running" });
				return;
			}

			if (subtype === "session_state_changed") {
				const state = msg.state as "idle" | "running" | "requires_action" | undefined;
				if (state) set({ sessionState: state });
				return;
			}

			if (subtype === "api_retry") {
				addItem({
					kind: "api-retry",
					id: uid(),
					attempt: Number(msg.attempt ?? 0),
					maxRetries: Number(msg.max_retries ?? 0),
					delayMs: Number(msg.retry_delay_ms ?? 0),
					error: String(msg.error ?? "unknown"),
				});
				return;
			}

			if (subtype === "hook_started") {
				addItem({
					kind: "hook",
					id: String(msg.hook_id || uid()),
					hookName: String(msg.hook_name || ""),
					hookEvent: String(msg.hook_event || ""),
					outcome: "started",
				});
				return;
			}

			if (subtype === "hook_progress") {
				const hookId = String(msg.hook_id || "");
				const stdout = String(msg.stdout || "");
				set((state) => ({
					items: state.items.map((item) =>
						item.kind === "hook" && item.id === hookId
							? { ...item, outcome: "progress" as const, stdout: stdout.slice(0, 160) }
							: item,
					),
				}));
				return;
			}

			if (subtype === "hook_response") {
				const hookId = String(msg.hook_id || "");
				const outcome = msg.outcome === "success" ? "success" : "error";
				const exitCode = typeof msg.exit_code === "number" ? msg.exit_code : null;
				set((state) => ({
					items: state.items.map((item) =>
						item.kind === "hook" && item.id === hookId
							? { ...item, outcome: outcome as "success" | "error", exitCode }
							: item,
					),
				}));
				return;
			}

			if (subtype === "task_started") {
				const taskId = String(msg.task_id || uid());
				const description = String(msg.description || "");
				const toolUseId = typeof msg.tool_use_id === "string" ? msg.tool_use_id : undefined;
				const task: ActiveTask = { taskId, description, toolUseId };
				set((state) => {
					const next = new Map(state.activeTasks);
					next.set(taskId, task);
					return { activeTasks: next };
				});
				addItem({ kind: "task-start", id: uid(), taskId, description });
				return;
			}

			if (subtype === "task_progress") {
				// Update tool summary text inside the timeline for the active task
				return;
			}

			if (subtype === "task_notification") {
				const taskId = String(msg.task_id || "");
				const status = (msg.status as "completed" | "failed" | "stopped") || "completed";
				const summary = String(msg.summary || "");
				set((state) => {
					const next = new Map(state.activeTasks);
					next.delete(taskId);
					return { activeTasks: next };
				});
				addItem({ kind: "task-end", id: uid(), taskId, status, summary });
				return;
			}

			if (subtype === "elicitation_complete") {
				set({ pendingElicitation: null });
				return;
			}

			if (subtype === "local_command_output") {
				addItem({
					kind: "system-notice",
					id: uid(),
					text: String(msg.content || ""),
					variant: "info",
				});
				return;
			}

			return;
		}

		// ── assistant turn (completed) ─────────────────────────────────────────
		if (type === "assistant") {
			const content = (msg.message as Record<string, unknown>)?.content;
			const streaming = get().streaming;
			const thinkingText = streaming.thinkingText;
			const toolUses = streaming.toolUses;

			// Flush any accumulated thinking block
			if (thinkingText) {
				addItem({
					kind: "thinking",
					id: uid(),
					data: { text: thinkingText, isStreaming: false, isRedacted: false },
				});
			}

			// Flush tool uses accumulated during streaming (SDK streaming mode only).
			// In CLI stream-json mode these are empty; tool_use comes from content blocks below.
			for (const [, tu] of toolUses) {
				addItem({ kind: "tool-use", id: uid(), tool: { ...tu, status: "completed" } });
				buildDiffForToolUse(tu, addItem);
			}

			// Flush accumulated streaming text (populated via appendStreamingText from
			// code-agent:token events which fire before this sdk-message arrives).
			const assistantText = streaming.assistantText;
			if (assistantText.trim()) {
				addItem({ kind: "assistant-text", id: uid(), text: assistantText, isStreaming: false });
			}

			// Reset streaming state
			set({ streaming: initialStreaming() });

			// In CLI stream-json mode there are no incremental stream events, so
			// streaming.toolUses and streaming.assistantText are empty.
			// Parse content blocks directly from the completed assistant message.
			if (Array.isArray(content)) {
				for (const block of content as Array<Record<string, unknown>>) {
					if (block.type === "text" && block.text && !assistantText) {
						// Only add text directly if streaming path didn't already flush it
						addItem({ kind: "assistant-text", id: uid(), text: String(block.text), isStreaming: false });
					}
					if (block.type === "tool_use" && toolUses.size === 0) {
						// CLI mode: tool uses come here, not from streaming events
						const toolUseId = String(block.id || uid());
						const toolName = String(block.name || "");
						const rawInput = (block.input as Record<string, unknown>) || {};
						const inputSummary = buildInputSummary(toolName, rawInput);
						const tu: StreamingToolUse = {
							toolUseId,
							toolName,
							inputSummary,
							rawInput,
							status: "completed",
						};
						addItem({ kind: "tool-use", id: uid(), tool: tu });
						buildDiffForToolUse(tu, addItem);
					}
					if (block.type === "thinking" && toolUses.size === 0 && !thinkingText) {
						addItem({
							kind: "thinking",
							id: uid(),
							data: { text: String(block.thinking || ""), isStreaming: false, isRedacted: false },
						});
					}
					if (block.type === "redacted_thinking") {
						addItem({
							kind: "thinking",
							id: uid(),
							data: { text: "", isStreaming: false, isRedacted: true },
						});
					}
				}
			}
			return;
		}

		// ── stream_event (incremental) ─────────────────────────────────────────
		if (type === "stream_event") {
			const event = msg.event as Record<string, unknown> | undefined;
			if (!event) return;
			const evType = String(event.type || "");

			if (evType === "content_block_start") {
				const block = event.content_block as Record<string, unknown> | undefined;
				if (!block) return;
				const blockType = String(block.type || "");
				if (blockType === "thinking") {
					set((state) => ({
						streaming: { ...state.streaming, isThinking: true, thinkingText: "", spinnerMode: "thinking" },
					}));
				} else if (blockType === "redacted_thinking") {
					addItem({
						kind: "thinking",
						id: uid(),
						data: { text: "", isStreaming: false, isRedacted: true },
					});
				} else if (blockType === "text") {
					set((state) => ({
						streaming: { ...state.streaming, isStreaming: true, spinnerMode: "responding" },
					}));
				} else if (blockType === "tool_use") {
					const toolUseId = String(block.id || uid());
					const toolName = String(block.name || "");
					const tu: StreamingToolUse = {
						toolUseId,
						toolName,
						inputSummary: "",
						rawInput: {},
						status: "streaming-input",
					};
					set((state) => {
						const next = new Map(state.streaming.toolUses);
						next.set(toolUseId, tu);
						return { streaming: { ...state.streaming, toolUses: next, spinnerMode: "tool-input" } };
					});
				}
				return;
			}

			if (evType === "content_block_delta") {
				const delta = event.delta as Record<string, unknown> | undefined;
				if (!delta) return;
				const deltaType = String(delta.type || "");

				if (deltaType === "thinking_delta") {
					const text = String(delta.thinking || "");
					set((state) => ({
						streaming: { ...state.streaming, thinkingText: state.streaming.thinkingText + text },
					}));
				} else if (deltaType === "text_delta") {
					const text = String(delta.text || "");
					set((state) => ({
						streaming: { ...state.streaming, assistantText: state.streaming.assistantText + text },
					}));
				}
				return;
			}

			if (evType === "content_block_stop") {
				const s = get().streaming;
				if (s.isThinking && s.thinkingText) {
					addItem({
						kind: "thinking",
						id: uid(),
						data: { text: s.thinkingText, isStreaming: false, isRedacted: false },
					});
					set((state) => ({
						streaming: { ...state.streaming, isThinking: false, thinkingText: "" },
					}));
				}
				return;
			}

			if (evType === "message_start") {
				set((state) => ({
					streaming: { ...state.streaming, spinnerMode: "requesting" },
				}));
			}

			if (evType === "message_delta") {
				set((state) => ({
					streaming: { ...state.streaming, spinnerMode: "responding" },
				}));
			}
			return;
		}

		// ── tool_progress ─────────────────────────────────────────────────────
		if (type === "tool_progress") {
			const toolUseId = String(msg.tool_use_id || "");
			const elapsed = Number(msg.elapsed_time_seconds ?? 0);
			set((state) => {
				if (!state.streaming.toolUses.has(toolUseId)) return state;
				const next = new Map(state.streaming.toolUses);
				const existing = next.get(toolUseId);
				if (existing) {
					next.set(toolUseId, { ...existing, elapsedSeconds: elapsed, status: "executing" });
				}
				return { streaming: { ...state.streaming, toolUses: next } };
			});
			return;
		}

		// ── result (turn complete) ─────────────────────────────────────────────
		if (type === "result") {
			const isError = Boolean(msg.is_error);
			const numTurns = Number(msg.num_turns ?? 0);
			const totalCostUsd = Number(msg.total_cost_usd ?? 0);
			const durationMs = Number(msg.duration_ms ?? 0);
			addItem({ kind: "result", id: uid(), isError, numTurns, totalCostUsd, durationMs });
			set({ sessionState: "idle", streaming: initialStreaming(), lastUpdatedAt: Date.now() });
			return;
		}

		// ── rate_limit_event ──────────────────────────────────────────────────
		if (type === "rate_limit_event") {
			const info = msg.rate_limit_info as Record<string, unknown> | undefined;
			const status = String(info?.status ?? "allowed");
			const resetsAt = typeof info?.resetsAt === "number" ? info.resetsAt : null;
			const utilization = typeof info?.utilization === "number" ? info.utilization : null;
			set({ rateLimitInfo: { status, resetsAt: resetsAt ?? undefined, utilization: utilization ?? undefined } });
			if (status === "rejected" || status === "allowed_warning") {
				addItem({
					kind: "rate-limit",
					id: uid(),
					resetsAt,
					utilization,
					status,
				});
			}
			return;
		}

		// ── auth_status ───────────────────────────────────────────────────────
		if (type === "auth_status") {
			const output = Array.isArray(msg.output) ? (msg.output as string[]).join("\n") : "";
			if (output) {
				addItem({ kind: "system-notice", id: uid(), text: output, variant: "info" });
			}
			return;
		}

		// ── user (tool_result or first user message) ──────────────────────────
		if (type === "user") {
			const message = msg.message as Record<string, unknown> | undefined;
			const content = message?.content;
			// Capture session title from the first plain text user message
			if (!get().sessionTitle && typeof content === "string" && content.trim()) {
				const title = content.trim().slice(0, 20);
				set({ sessionTitle: title });
			} else if (!get().sessionTitle && Array.isArray(content)) {
				const textBlock = (content as Array<Record<string, unknown>>).find(
					(b) => b.type === "text" && typeof b.text === "string" && (b.text as string).trim(),
				);
				if (textBlock) {
					const title = (textBlock.text as string).trim().slice(0, 20);
					set({ sessionTitle: title });
				}
			}
			if (Array.isArray(content)) {
				for (const block of content as Array<Record<string, unknown>>) {
					if (block.type === "tool_result") {
						const toolUseId = String(block.tool_use_id || "");
						const resultText = extractTextContent(block.content);
						// Update the completed tool-use item in the timeline with result info
						set((state) => ({
							items: state.items.map((item) =>
								item.kind === "tool-use" && item.tool.toolUseId === toolUseId
									? {
											...item,
											tool: {
												...item.tool,
												status: "completed" as const,
												resultSummary: resultText.slice(0, 120),
											},
										}
									: item,
							),
						}));
					}
				}
			}
			return;
		}
	},
}));
