/**
 * Zustand store for Claude Code CLI agent state.
 *
 * Receives raw SDK messages from `code-agent:sdk-message` IPC events and
 * transforms them into structured UI state consumed by MiniChat components.
 */
import { create } from "zustand";
import type { Descendant } from "slate";

// ─── SDK message shape helpers ───────────────────────────────────────────────
// We do not import the full Zod schemas here to keep the renderer bundle lean.
// Instead, we type-narrow on `type` + `subtype` discriminants at runtime.

export type SdkMessageType =
	| "assistant"
	| "user"
	| "stream_event"
	| "result"
	| "system"
	| "tool_progress"
	| "tool_use_summary"
	| "rate_limit_event"
	| "auth_status"
	| "prompt_suggestion";

export type RawSdkMessage = Record<string, unknown> & { type: SdkMessageType };

// ─── Timeline item types ─────────────────────────────────────────────────────

export type SpinnerMode =
	| "requesting"
	| "thinking"
	| "tool-input"
	| "tool-use"
	| "responding"
	| null;

export type VendorStatusSource = "vendor" | "fallback" | null;

const SPINNER_VERBS = [
	"Accomplishing",
	"Actioning",
	"Actualizing",
	"Architecting",
	"Baking",
	"Beaming",
	"Beboppin'",
	"Befuddling",
	"Billowing",
	"Blanching",
	"Bloviating",
	"Boogieing",
	"Boondoggling",
	"Booping",
	"Bootstrapping",
	"Brewing",
	"Bunning",
	"Burrowing",
	"Calculating",
	"Canoodling",
	"Caramelizing",
	"Cascading",
	"Catapulting",
	"Cerebrating",
	"Channeling",
	"Channelling",
	"Choreographing",
	"Churning",
	"Clauding",
	"Coalescing",
	"Cogitating",
	"Combobulating",
	"Composing",
	"Computing",
	"Concocting",
	"Considering",
	"Contemplating",
	"Cooking",
	"Crafting",
	"Creating",
	"Crunching",
	"Crystallizing",
	"Cultivating",
	"Deciphering",
	"Deliberating",
	"Determining",
	"Dilly-dallying",
	"Discombobulating",
	"Doing",
	"Doodling",
	"Drizzling",
	"Ebbing",
	"Effecting",
	"Elucidating",
	"Embellishing",
	"Enchanting",
	"Envisioning",
	"Evaporating",
	"Fermenting",
	"Fiddle-faddling",
	"Finagling",
	"Flambéing",
	"Flibbertigibbeting",
	"Flowing",
	"Flummoxing",
	"Fluttering",
	"Forging",
	"Forming",
	"Frolicking",
	"Frosting",
	"Gallivanting",
	"Galloping",
	"Garnishing",
	"Generating",
	"Gesticulating",
	"Germinating",
	"Gitifying",
	"Grooving",
	"Gusting",
	"Harmonizing",
	"Hashing",
	"Hatching",
	"Herding",
	"Honking",
	"Hullaballooing",
	"Hyperspacing",
	"Ideating",
	"Imagining",
	"Improvising",
	"Incubating",
	"Inferring",
	"Infusing",
	"Ionizing",
	"Jitterbugging",
	"Julienning",
	"Kneading",
	"Leavening",
	"Levitating",
	"Lollygagging",
	"Manifesting",
	"Marinating",
	"Meandering",
	"Metamorphosing",
	"Misting",
	"Moonwalking",
	"Moseying",
	"Mulling",
	"Mustering",
	"Musing",
	"Nebulizing",
	"Nesting",
	"Newspapering",
	"Noodling",
	"Nucleating",
	"Orbiting",
	"Orchestrating",
	"Osmosing",
	"Perambulating",
	"Percolating",
	"Perusing",
	"Philosophising",
	"Photosynthesizing",
	"Pollinating",
	"Pondering",
	"Pontificating",
	"Pouncing",
	"Precipitating",
	"Prestidigitating",
	"Processing",
	"Proofing",
	"Propagating",
	"Puttering",
	"Puzzling",
	"Quantumizing",
	"Razzle-dazzling",
	"Razzmatazzing",
	"Recombobulating",
	"Reticulating",
	"Roosting",
	"Ruminating",
	"Sautéing",
	"Scampering",
	"Schlepping",
	"Scurrying",
	"Seasoning",
	"Shenaniganing",
	"Shimmying",
	"Simmering",
	"Skedaddling",
	"Sketching",
	"Slithering",
	"Smooshing",
	"Sock-hopping",
	"Spelunking",
	"Spinning",
	"Sprouting",
	"Stewing",
	"Sublimating",
	"Swirling",
	"Swooping",
	"Symbioting",
	"Synthesizing",
	"Tempering",
	"Thinking",
	"Thundering",
	"Tinkering",
	"Tomfoolering",
	"Topsy-turvying",
	"Transfiguring",
	"Transmuting",
	"Twisting",
	"Undulating",
	"Unfurling",
	"Unravelling",
	"Vibing",
	"Waddling",
	"Wandering",
	"Warping",
	"Whatchamacalliting",
	"Whirlpooling",
	"Whirring",
	"Whisking",
	"Wibbling",
	"Working",
	"Wrangling",
	"Zesting",
	"Zigzagging",
] as const;

export type ToolStatus =
	| "streaming-input"
	| "executing"
	| "awaiting-permission"
	| "completed"
	| "failed";

export type StreamingToolUse = {
	toolUseId: string;
	toolName: string;
	inputSummary: string;
	rawInput: Record<string, unknown>;
	status: ToolStatus;
	resultSummary?: string;
	/** Elapsed seconds from tool_progress heartbeats */
	elapsedSeconds?: number;
};

export type ThinkingBlockData = {
	text: string;
	isStreaming: boolean;
	isRedacted: boolean;
};

export type DiffFile = {
	filePath: string;
	additions: number;
	deletions: number;
	/** Unified diff patch string generated by the `diff` package */
	patch: string;
};

export type CodeAgentUserImagePreview = {
	preview: string | null;
	fileName: string;
};

export type CodeAgentUserPathTag = {
	absolutePath: string;
	name: string;
	isDirectory: boolean;
};

export type CodeAgentUserMessageMeta = {
	imagePreviews?: CodeAgentUserImagePreview[];
	pathTags?: CodeAgentUserPathTag[];
	richContent?: Descendant[];
};

/** Items that form the visual timeline in CodeTimeline */
export type CodeAgentTimelineItem =
	| { kind: "init"; id: string; model: string; permissionMode: string; toolCount: number; mcpCount: number; cwd: string }
	| { kind: "thinking"; id: string; data: ThinkingBlockData }
	| { kind: "assistant-text"; id: string; text: string; isStreaming: boolean }
	| { kind: "tool-use"; id: string; tool: StreamingToolUse }
	| { kind: "diff"; id: string; files: DiffFile[] }
	| {
		kind: "user";
		id: string;
		text: string;
		imagePreviews?: CodeAgentUserImagePreview[];
		pathTags?: CodeAgentUserPathTag[];
		richContent?: Descendant[];
	}
	| { kind: "system-notice"; id: string; text: string; variant?: "info" | "warning" | "error" }
	| { kind: "compact-boundary"; id: string; preTokens: number; trigger: string }
	| { kind: "rate-limit"; id: string; resetsAt: number | null; utilization: number | null; status: string }
	| { kind: "api-retry"; id: string; attempt: number; maxRetries: number; delayMs: number; error: string }
	| { kind: "hook"; id: string; hookName: string; hookEvent: string; outcome: "started" | "progress" | "success" | "error"; stdout?: string; exitCode?: number | null }
	| { kind: "task-start"; id: string; taskId: string; description: string }
	| { kind: "task-end"; id: string; taskId: string; status: "completed" | "failed" | "stopped"; summary: string }
	| { kind: "result"; id: string; isError: boolean; numTurns: number; totalCostUsd: number; durationMs: number }
	| { kind: "permission-request"; id: string; requestId: string; toolName: string; rawInput: Record<string, unknown>; title?: string; description?: string }
	| { kind: "elicitation"; id: string; elicitationId: string; mcpServerName: string; message: string; requestedSchema: Record<string, unknown> | null };

// ─── Session init info ────────────────────────────────────────────────────────
export type SessionInitInfo = {
	model: string;
	permissionMode: string;
	tools: string[];
	mcpServers: Array<{ name: string; status: string }>;
	cwd: string;
	claudeCodeVersion: string;
};

// ─── Elicitation request ─────────────────────────────────────────────────────
export type PendingElicitation = {
	elicitationId: string;
	mcpServerName: string;
	message: string;
	requestedSchema: Record<string, unknown> | null;
	mode?: string;
};

// ─── Permission request ───────────────────────────────────────────────────────
export type PendingPermission = {
	requestId: string;
	toolName: string;
	rawInput: Record<string, unknown>;
	inputSummary: string;
	title?: string;
	description?: string;
};

// ─── Active subagent task ─────────────────────────────────────────────────────
export type ActiveTask = {
	taskId: string;
	description: string;
	toolUseId?: string;
};

// ─── Rate-limit state ─────────────────────────────────────────────────────────
export type RateLimitInfo = {
	status: string;
	resetsAt?: number;
	utilization?: number;
};

export type CodeAgentContextWindowUsage = {
	/** Model context window size (tokens). */
	contextWindowSize: number;
	/** Whether window size came from SDK payload or local fallback inference. */
	windowSource: "reported" | "estimated";
	model: string | null;
	inputTokens: number;
	outputTokens: number;
	cacheReadInputTokens: number;
	cacheCreationInputTokens: number;
	/** Current prompt footprint used to estimate context pressure. */
	usedTokens: number;
	remainingTokens: number;
	usedPercentage: number;
	remainingPercentage: number;
	updatedAt: number;
};

// ─── Store interface ──────────────────────────────────────────────────────────
export interface CodeAgentStore {
	// Session metadata
	sessionId: string | null;
	sessionInit: SessionInitInfo | null;
	sessionState: "idle" | "running" | "requires_action";
	/** Title derived from the first user message in this session (first 20 chars) */
	sessionTitle: string | null;
	/** Timestamp (ms) of when the last result message was received */
	lastUpdatedAt: number | null;

	// Full message timeline
	items: CodeAgentTimelineItem[];

	// Current turn streaming state
	streaming: {
		thinkingText: string;
		isThinking: boolean;
		assistantText: string;
		isStreaming: boolean;
		spinnerMode: SpinnerMode;
		vendorStatusText: string;
		vendorStatusSource: VendorStatusSource;
		/** Active tool uses keyed by tool_use_id */
		toolUses: Map<string, StreamingToolUse>;
	};

	// Pending user interactions
	pendingPermission: PendingPermission | null;
	pendingElicitation: PendingElicitation | null;

	// Subagent tasks currently running
	activeTasks: Map<string, ActiveTask>;

	// Rate limit state
	rateLimitInfo: RateLimitInfo | null;
	contextUsage: CodeAgentContextWindowUsage | null;

	// Session-level auto-approved tool types (cleared on reset)
	sessionAllowedTools: Set<string>;

	// Actions
	pushSdkMessage: (raw: unknown) => void;
	pushUserMessage: (text: string, meta?: CodeAgentUserMessageMeta) => void;
	/** Append incremental text from `code-agent:token` IPC events for live streaming */
	appendStreamingText: (text: string) => void;
	setPendingPermission: (p: PendingPermission | null) => void;
	resolvePermission: (requestId: string, _decision: "allow" | "allow-session" | "deny") => void;
	resolveElicitation: (action: "accept" | "decline", content?: Record<string, unknown>) => void;
	addSessionAllowedTool: (toolName: string) => void;
	/** Full reset — clears items + streaming + session state */
	reset: () => void;
	/** Light reset — clears only streaming state, keeps items for persistent timeline */
	resetStreaming: () => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uid() {
	return crypto.randomUUID();
}

function extractTextContent(value: unknown): string {
	if (!value) return "";
	if (typeof value === "string") return value;
	if (Array.isArray(value)) {
		return value
			.map((item) => {
				if (typeof item === "string") return item;
				if (item && typeof (item as Record<string, unknown>).text === "string")
					return (item as Record<string, unknown>).text as string;
				return "";
			})
			.filter(Boolean)
			.join("\n");
	}
	if (typeof value === "object") {
		const obj = value as Record<string, unknown>;
		if (typeof obj.text === "string") return obj.text;
	}
	return "";
}

/** Build a short display summary for a tool's input parameters */
export function buildInputSummary(toolName: string, input: Record<string, unknown>): string {
	if (!input) return "";
	const name = toolName.toLowerCase();
	const truncate = (s: string, max = 80) =>
		s.length > max ? `${s.slice(0, max)}…` : s;

	const str = (v: unknown) => (typeof v === "string" ? v : "");

	if (["read", "write", "edit", "multiedit", "notebookedit"].includes(name)) {
		return truncate(str(input.file_path) || str(input.path));
	}
	if (name === "bash") return truncate(str(input.command), 72);
	if (name === "grep") {
		const pat = str(input.pattern);
		const path = str(input.path);
		return pat ? truncate(path ? `"${pat}" in ${path}` : `"${pat}"`) : "";
	}
	if (name === "glob") {
		const glob = str(input.pattern) || str(input.glob_pattern);
		const dir = str(input.path) || str(input.target_directory);
		return truncate(dir ? `${glob} in ${dir}` : glob);
	}
	if (name === "webfetch") return truncate(str(input.url));
	if (name === "agent" || name === "task") return truncate(str(input.description) || str(input.prompt), 60);
	const first = Object.values(input).find((v) => typeof v === "string" && (v as string).length > 0);
	return first ? truncate(first as string) : "";
}

/** Generate unified diff patch string between two text buffers */
function buildUnifiedPatch(
	filePath: string,
	oldContent: string,
	newContent: string,
): { patch: string; additions: number; deletions: number } {
	const oldLines = oldContent.split("\n");
	const newLines = newContent.split("\n");
	let additions = 0;
	let deletions = 0;

	// Simple line-diff to produce unified output
	// In practice the `diff` npm package should be used for robust output;
	// this is a lightweight fallback so no extra dependency is required at
	// compile time in the renderer. The DiffView component can also use
	// the `diff` package directly if available.
	const lines: string[] = [`--- a/${filePath}`, `+++ b/${filePath}`];
	const maxLen = Math.max(oldLines.length, newLines.length);
	for (let i = 0; i < maxLen; i++) {
		if (i < oldLines.length && i < newLines.length) {
			if (oldLines[i] !== newLines[i]) {
				lines.push(`-${oldLines[i]}`);
				lines.push(`+${newLines[i]}`);
				deletions++;
				additions++;
			} else {
				lines.push(` ${oldLines[i]}`);
			}
		} else if (i < newLines.length) {
			lines.push(`+${newLines[i]}`);
			additions++;
		} else {
			lines.push(`-${oldLines[i]}`);
			deletions++;
		}
	}

	return { patch: lines.join("\n"), additions, deletions };
}

/** Extract and add a diff item for file-edit/write tool uses */
function buildDiffForToolUse(
	tu: StreamingToolUse,
	addItem: (item: CodeAgentTimelineItem) => void,
) {
	const name = tu.toolName.toLowerCase();
	const isFileEdit = ["edit", "fileedit", "strreplacebasededitattempt", "multiedit", "write", "filewrite"].includes(name);
	if (!isFileEdit || !tu.rawInput) return;
	const filePath = String(tu.rawInput.file_path || tu.rawInput.path || "");
	const oldContent = String(tu.rawInput.old_content || tu.rawInput.old_string || "");
	const newContent = String(tu.rawInput.new_content || tu.rawInput.new_string || tu.rawInput.content || "");
	if (!filePath || !(oldContent || newContent)) return;
	const { patch, additions, deletions } = buildUnifiedPatch(filePath, oldContent, newContent);
	if (additions + deletions > 0) {
		addItem({ kind: "diff", id: uid(), files: [{ filePath, additions, deletions, patch }] });
	}
}

// ─── Initial state factory ────────────────────────────────────────────────────
function sampleSpinnerVerb(): string {
	return SPINNER_VERBS[Math.floor(Math.random() * SPINNER_VERBS.length)] || "Thinking";
}

function buildFallbackVendorStatus(
	spinnerMode: SpinnerMode,
	currentVendorStatusText = "",
): string {
	switch (spinnerMode) {
		case "requesting":
		case "thinking": {
			const normalized = currentVendorStatusText.trim();
			if (normalized.startsWith("✶ ") && normalized.endsWith("…")) {
				return normalized.slice(2, -1).trim();
			}
			if (normalized) {
				return normalized.replace(/[.…]+$/u, "").trim();
			}
			return sampleSpinnerVerb();
		}
		case "tool-input":
			return "Preparing tool input";
		case "tool-use":
			return "Using tools";
		case "responding":
			return "Responding";
		default:
			return "";
	}
}

function formatVendorStatusLabel(statusText: string): string {
	const normalized = statusText.trim().replace(/[.…]+$/u, "");
	if (!normalized) return "";
	return `✶ ${normalized}…`;
}

function extractVendorStatus(msg: Record<string, unknown>): string {
	const direct = typeof msg.vendorStatusText === "string" ? msg.vendorStatusText : "";
	if (direct.trim()) return direct.trim();

	const nested = msg.meta;
	if (nested && typeof nested === "object") {
		const metaStatus = (nested as Record<string, unknown>).vendorStatusText;
		if (typeof metaStatus === "string" && metaStatus.trim()) {
			return metaStatus.trim();
		}
	}

	return "";
}

const DEFAULT_CONTEXT_WINDOW_TOKENS = 200_000;

function asRecord(value: unknown): Record<string, unknown> | null {
	return value && typeof value === "object" ? (value as Record<string, unknown>) : null;
}

function toFiniteNumber(value: unknown): number | null {
	if (typeof value === "number" && Number.isFinite(value)) return value;
	if (typeof value === "string") {
		const parsed = Number(value);
		if (Number.isFinite(parsed)) return parsed;
	}
	return null;
}

function pickNumber(record: Record<string, unknown> | null, keys: string[]): number | null {
	if (!record) return null;
	for (const key of keys) {
		const num = toFiniteNumber(record[key]);
		if (num != null) return num;
	}
	return null;
}

function extractLastIterationUsage(record: Record<string, unknown> | null): {
	inputTokens: number;
	outputTokens: number;
} | null {
	if (!record || !Array.isArray(record.iterations) || record.iterations.length === 0) {
		return null;
	}
	for (let index = record.iterations.length - 1; index >= 0; index -= 1) {
		const iteration = asRecord(record.iterations[index]);
		if (!iteration) continue;
		const inputTokens = pickNumber(iteration, ["input_tokens", "inputTokens", "input"]);
		const outputTokens = pickNumber(iteration, ["output_tokens", "outputTokens", "output"]);
		if (inputTokens == null && outputTokens == null) continue;
		return {
			inputTokens: Math.max(0, Math.round(inputTokens ?? 0)),
			outputTokens: Math.max(0, Math.round(outputTokens ?? 0)),
		};
	}
	return null;
}

function extractUsageShape(record: Record<string, unknown> | null): {
	inputTokens: number;
	outputTokens: number;
	cacheReadInputTokens: number;
	cacheCreationInputTokens: number;
} | null {
	if (!record) return null;
	const inputTokens = pickNumber(record, ["input_tokens", "inputTokens", "input"]);
	const outputTokens = pickNumber(record, ["output_tokens", "outputTokens", "output"]);
	const iterationUsage = extractLastIterationUsage(record);
	const resolvedInputTokens =
		(inputTokens != null && inputTokens > 0)
			? inputTokens
			: iterationUsage?.inputTokens ?? inputTokens;
	const resolvedOutputTokens =
		(outputTokens != null && outputTokens > 0)
			? outputTokens
			: iterationUsage?.outputTokens ?? outputTokens;
	const cacheReadInputTokens =
		pickNumber(record, ["cache_read_input_tokens", "cacheReadInputTokens", "cacheRead"]) ?? 0;
	const cacheCreationInputTokens =
		pickNumber(record, ["cache_creation_input_tokens", "cacheCreationInputTokens", "cacheWrite"]) ?? 0;

	if (resolvedInputTokens == null && resolvedOutputTokens == null) return null;
	return {
		inputTokens: Math.max(0, Math.round(resolvedInputTokens ?? 0)),
		outputTokens: Math.max(0, Math.round(resolvedOutputTokens ?? 0)),
		cacheReadInputTokens: Math.max(0, Math.round(cacheReadInputTokens)),
		cacheCreationInputTokens: Math.max(0, Math.round(cacheCreationInputTokens)),
	};
}

function inferContextWindowFromModel(model: string | null): number {
	if (model && /\[1m\]/i.test(model)) return 1_000_000;
	return DEFAULT_CONTEXT_WINDOW_TOKENS;
}

function clampPercent(value: number): number {
	if (!Number.isFinite(value)) return 0;
	return Math.max(0, Math.min(100, Math.round(value)));
}

function extractContextUsage(
	msg: Record<string, unknown>,
	fallbackModel: string | null,
	previousUsage: CodeAgentContextWindowUsage | null,
): CodeAgentContextWindowUsage | null {
	const message = asRecord(msg.message);
	const request = asRecord(msg.request);
	const event = asRecord(msg.event);
	const contextWindow = asRecord(msg.context_window) ?? asRecord(message?.context_window) ?? asRecord(request?.context_window);
	const usage =
		extractUsageShape(asRecord(contextWindow?.current_usage))
		?? extractUsageShape(asRecord(event?.usage))
		?? extractUsageShape(asRecord(asRecord(event?.message)?.usage))
		?? extractUsageShape(asRecord(message?.usage))
		?? extractUsageShape(asRecord(msg.usage));

	if (!usage) return null;

	const model =
		typeof message?.model === "string"
			? message.model
			: typeof msg.model === "string"
				? (msg.model as string)
				: fallbackModel;

	const reportedWindowSize = pickNumber(contextWindow, ["context_window_size", "contextWindowSize"]);
	const contextWindowSize = Math.max(
		1,
		Math.round(reportedWindowSize ?? inferContextWindowFromModel(model)),
	);
	const usedTokens = Math.max(
		0,
		usage.inputTokens + usage.cacheReadInputTokens + usage.cacheCreationInputTokens,
	);
	const remainingTokens = Math.max(0, contextWindowSize - usedTokens);

	const usedPercentageFromPayload = pickNumber(contextWindow, ["used_percentage", "usedPercentage"]);
	const remainingPercentageFromPayload = pickNumber(contextWindow, ["remaining_percentage", "remainingPercentage"]);
	const usedPercentage = clampPercent(
		usedPercentageFromPayload ?? (usedTokens / contextWindowSize) * 100,
	);
	const remainingPercentage = clampPercent(
		remainingPercentageFromPayload ?? 100 - usedPercentage,
	);
	const hasExplicitContextWindowUsage = Boolean(
		contextWindow && (
			asRecord(contextWindow.current_usage)
			|| pickNumber(contextWindow, ["used_percentage", "usedPercentage"]) != null
			|| pickNumber(contextWindow, ["remaining_percentage", "remainingPercentage"]) != null
			|| pickNumber(contextWindow, ["total_input_tokens", "totalInputTokens"]) != null
			|| pickNumber(contextWindow, ["total_output_tokens", "totalOutputTokens"]) != null
		),
	);

	// Some providers emit output-only usage records (input/cache = 0) for
	// assistant turns. If we overwrite with these records, the UI jumps back to
	// "200k remaining". Keep the previous session footprint unless payload gives
	// explicit context-window metrics.
	if (usedTokens === 0 && !hasExplicitContextWindowUsage && previousUsage) {
		return null;
	}

	return {
		contextWindowSize,
		windowSource: reportedWindowSize != null ? "reported" : "estimated",
		model: model ?? null,
		inputTokens: usage.inputTokens,
		outputTokens: usage.outputTokens,
		cacheReadInputTokens: usage.cacheReadInputTokens,
		cacheCreationInputTokens: usage.cacheCreationInputTokens,
		usedTokens,
		remainingTokens,
		usedPercentage,
		remainingPercentage,
		updatedAt: Date.now(),
	};
}

function initialStreaming() {
	return {
		thinkingText: "",
		isThinking: false,
		assistantText: "",
		isStreaming: false,
		spinnerMode: null as SpinnerMode,
		vendorStatusText: "",
		vendorStatusSource: null as VendorStatusSource,
		toolUses: new Map<string, StreamingToolUse>(),
	};
}
// ─── Store ────────────────────────────────────────────────────────────────────
export const useCodeAgentStore = create<CodeAgentStore>((set, get) => ({
	sessionId: null,
	sessionInit: null,
	sessionState: "idle",
	sessionTitle: null,
	lastUpdatedAt: null,
	items: [],
	streaming: initialStreaming(),
	pendingPermission: null,
	pendingElicitation: null,
	activeTasks: new Map(),
	rateLimitInfo: null,
	contextUsage: null,
	sessionAllowedTools: new Set(),

	reset: () => {
		set({
			sessionId: null,
			sessionInit: null,
			sessionState: "idle",
			sessionTitle: null,
			lastUpdatedAt: null,
			items: [],
			streaming: initialStreaming(),
			pendingPermission: null,
			pendingElicitation: null,
				activeTasks: new Map(),
				rateLimitInfo: null,
				contextUsage: null,
				sessionAllowedTools: new Set(),
			});
		},

	resetStreaming: () => {
			set({
				streaming: initialStreaming(),
				pendingPermission: null,
				pendingElicitation: null,
				rateLimitInfo: null,
			});
		},

	appendStreamingText: (text) => {
		set((state) => ({
			streaming: {
				...state.streaming,
				assistantText: state.streaming.assistantText + text,
				isStreaming: true,
				spinnerMode: "responding",
				vendorStatusText:
					state.streaming.vendorStatusSource === "vendor"
						? state.streaming.vendorStatusText
						: formatVendorStatusLabel(buildFallbackVendorStatus("responding")),
				vendorStatusSource:
					state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
			},
		}));
	},

	setPendingPermission: (p) => {
		set({ pendingPermission: p });
	},

	resolvePermission: (requestId, _decision) => {
		const current = get().pendingPermission;
		if (current?.requestId === requestId) {
			set({ pendingPermission: null });
		}
		// Remove any pending permission item from timeline so the card disappears
		set((state) => ({
			items: state.items.filter(
				(item) =>
					!(item.kind === "permission-request" && item.requestId === requestId),
			),
		}));
	},

	resolveElicitation: (_action, _content) => {
		set({ pendingElicitation: null });
		set((state) => ({
			items: state.items.filter((item) => item.kind !== "elicitation"),
		}));
	},

	addSessionAllowedTool: (toolName) => {
		set((state) => {
			const next = new Set(state.sessionAllowedTools);
			next.add(toolName.toLowerCase());
			return { sessionAllowedTools: next };
		});
	},

	pushUserMessage: (text, meta) => {
		const imagePreviews = meta?.imagePreviews?.length ? meta.imagePreviews : undefined;
		const pathTags = meta?.pathTags?.length ? meta.pathTags : undefined;
		const richContent = meta?.richContent?.length ? meta.richContent : undefined;
		set((state) => ({
			items: [
				...state.items,
				{
					kind: "user",
					id: uid(),
					text,
					imagePreviews,
					pathTags,
					richContent,
				},
			],
		}));
	},

	pushSdkMessage: (raw) => {
		if (!raw || typeof raw !== "object") return;
		const msg = raw as Record<string, unknown>;
		const type = msg.type as string | undefined;
		if (!type) return;

			const vendorStatusText = extractVendorStatus(msg);
			if (vendorStatusText) {
				set((state) => ({
					streaming: {
						...state.streaming,
						vendorStatusText: formatVendorStatusLabel(vendorStatusText),
						vendorStatusSource: "vendor",
					},
				}));
			}

			const contextUsage = extractContextUsage(
				msg,
				get().sessionInit?.model ?? null,
				get().contextUsage,
			);
			if (contextUsage) {
				set({ contextUsage });
			}

		const addItem = (item: CodeAgentTimelineItem) => {
			set((state) => ({ items: [...state.items, item] }));
		};

		// ── system messages ────────────────────────────────────────────────────
		if (type === "system") {
			const subtype = msg.subtype as string | undefined;

			if (subtype === "init") {
				const tools = Array.isArray(msg.tools) ? (msg.tools as string[]) : [];
				const mcpServers = Array.isArray(msg.mcp_servers)
					? (msg.mcp_servers as Array<{ name: string; status: string }>)
					: [];
				const init: SessionInitInfo = {
					model: String(msg.model || ""),
					permissionMode: String(msg.permissionMode || "default"),
					tools,
					mcpServers,
					cwd: String(msg.cwd || ""),
					claudeCodeVersion: String(msg.claude_code_version || ""),
				};
				set({
					sessionId: String(msg.session_id || ""),
					sessionInit: init,
				});
				addItem({
					kind: "init",
					id: uid(),
					model: init.model,
					permissionMode: init.permissionMode,
					toolCount: tools.length,
					mcpCount: mcpServers.length,
					cwd: init.cwd,
				});
				return;
			}

			if (subtype === "compact_boundary") {
				const meta = msg.compact_metadata as Record<string, unknown> | undefined;
				addItem({
					kind: "compact-boundary",
					id: uid(),
					preTokens: Number(meta?.pre_tokens ?? 0),
					trigger: String(meta?.trigger ?? "auto"),
				});
				return;
			}

			if (subtype === "status") {
				const s = msg.status;
				if (s === "compacting") {
					addItem({ kind: "system-notice", id: uid(), text: "⟳ 正在压缩上下文…", variant: "info" });
				}
				set((state) => ({
					sessionState: s === null ? "idle" : "running",
					streaming:
						s === null
							? initialStreaming()
							: {
								...state.streaming,
								vendorStatusText:
									state.streaming.vendorStatusSource === "vendor"
										? state.streaming.vendorStatusText
										: formatVendorStatusLabel(buildFallbackVendorStatus(state.streaming.spinnerMode)),
								vendorStatusSource:
									state.streaming.vendorStatusSource === "vendor"
										? "vendor"
										: state.streaming.spinnerMode
											? "fallback"
											: null,
							},
				}));
				return;
			}

			if (subtype === "session_state_changed") {
				const state = msg.state as "idle" | "running" | "requires_action" | undefined;
				if (state) set({ sessionState: state });
				return;
			}

			if (subtype === "api_retry") {
				addItem({
					kind: "api-retry",
					id: uid(),
					attempt: Number(msg.attempt ?? 0),
					maxRetries: Number(msg.max_retries ?? 0),
					delayMs: Number(msg.retry_delay_ms ?? 0),
					error: String(msg.error ?? "unknown"),
				});
				return;
			}

			if (subtype === "hook_started") {
				addItem({
					kind: "hook",
					id: String(msg.hook_id || uid()),
					hookName: String(msg.hook_name || ""),
					hookEvent: String(msg.hook_event || ""),
					outcome: "started",
				});
				return;
			}

			if (subtype === "hook_progress") {
				const hookId = String(msg.hook_id || "");
				const stdout = String(msg.stdout || "");
				set((state) => ({
					items: state.items.map((item) =>
						item.kind === "hook" && item.id === hookId
							? { ...item, outcome: "progress" as const, stdout: stdout.slice(0, 160) }
							: item,
					),
				}));
				return;
			}

			if (subtype === "hook_response") {
				const hookId = String(msg.hook_id || "");
				const outcome = msg.outcome === "success" ? "success" : "error";
				const exitCode = typeof msg.exit_code === "number" ? msg.exit_code : null;
				set((state) => ({
					items: state.items.map((item) =>
						item.kind === "hook" && item.id === hookId
							? { ...item, outcome: outcome as "success" | "error", exitCode }
							: item,
					),
				}));
				return;
			}

			if (subtype === "task_started") {
				const taskId = String(msg.task_id || uid());
				const description = String(msg.description || "");
				const toolUseId = typeof msg.tool_use_id === "string" ? msg.tool_use_id : undefined;
				const task: ActiveTask = { taskId, description, toolUseId };
				set((state) => {
					const next = new Map(state.activeTasks);
					next.set(taskId, task);
					return { activeTasks: next };
				});
				addItem({ kind: "task-start", id: uid(), taskId, description });
				return;
			}

			if (subtype === "task_progress") {
				// Update tool summary text inside the timeline for the active task
				return;
			}

			if (subtype === "task_notification") {
				const taskId = String(msg.task_id || "");
				const status = (msg.status as "completed" | "failed" | "stopped") || "completed";
				const summary = String(msg.summary || "");
				set((state) => {
					const next = new Map(state.activeTasks);
					next.delete(taskId);
					return { activeTasks: next };
				});
				addItem({ kind: "task-end", id: uid(), taskId, status, summary });
				return;
			}

			if (subtype === "elicitation_complete") {
				set({ pendingElicitation: null });
				return;
			}

			if (subtype === "local_command_output") {
				addItem({
					kind: "system-notice",
					id: uid(),
					text: String(msg.content || ""),
					variant: "info",
				});
				return;
			}

			return;
		}

		// ── assistant turn (completed) ─────────────────────────────────────────
		if (type === "assistant") {
			const content = (msg.message as Record<string, unknown>)?.content;
			const streaming = get().streaming;
			const thinkingText = streaming.thinkingText;
			const toolUses = streaming.toolUses;

			// Flush any accumulated thinking block
			if (thinkingText) {
				addItem({
					kind: "thinking",
					id: uid(),
					data: { text: thinkingText, isStreaming: false, isRedacted: false },
				});
			}

			// Flush tool uses accumulated during streaming (SDK streaming mode only).
			// In CLI stream-json mode these are empty; tool_use comes from content blocks below.
			for (const [, tu] of toolUses) {
				addItem({ kind: "tool-use", id: uid(), tool: { ...tu, status: "completed" } });
				buildDiffForToolUse(tu, addItem);
			}

			// Flush accumulated streaming text (populated via appendStreamingText from
			// code-agent:token events which fire before this sdk-message arrives).
			const assistantText = streaming.assistantText;
			if (assistantText.trim()) {
				addItem({ kind: "assistant-text", id: uid(), text: assistantText, isStreaming: false });
			}

			// Reset streaming state
			set({ streaming: initialStreaming() });

			// In CLI stream-json mode there are no incremental stream events, so
			// streaming.toolUses and streaming.assistantText are empty.
			// Parse content blocks directly from the completed assistant message.
			if (Array.isArray(content)) {
				for (const block of content as Array<Record<string, unknown>>) {
					if (block.type === "text" && block.text && !assistantText) {
						// Only add text directly if streaming path didn't already flush it
						addItem({ kind: "assistant-text", id: uid(), text: String(block.text), isStreaming: false });
					}
					if (block.type === "tool_use" && toolUses.size === 0) {
						// CLI mode: tool uses come here, not from streaming events
						const toolUseId = String(block.id || uid());
						const toolName = String(block.name || "");
						const rawInput = (block.input as Record<string, unknown>) || {};
						const inputSummary = buildInputSummary(toolName, rawInput);
						const tu: StreamingToolUse = {
							toolUseId,
							toolName,
							inputSummary,
							rawInput,
							status: "completed",
						};
						addItem({ kind: "tool-use", id: uid(), tool: tu });
						buildDiffForToolUse(tu, addItem);
					}
					if (block.type === "thinking" && toolUses.size === 0 && !thinkingText) {
						addItem({
							kind: "thinking",
							id: uid(),
							data: { text: String(block.thinking || ""), isStreaming: false, isRedacted: false },
						});
					}
					if (block.type === "redacted_thinking") {
						addItem({
							kind: "thinking",
							id: uid(),
							data: { text: "", isStreaming: false, isRedacted: true },
						});
					}
				}
			}
			return;
		}

		// ── stream_event (incremental) ─────────────────────────────────────────
		if (type === "stream_event") {
			const event = msg.event as Record<string, unknown> | undefined;
			if (!event) return;
			const evType = String(event.type || "");

			if (evType === "content_block_start") {
				const block = event.content_block as Record<string, unknown> | undefined;
				if (!block) return;
				const blockType = String(block.type || "");
				if (blockType === "thinking") {
					set((state) => ({
						streaming: {
							...state.streaming,
							isThinking: true,
							thinkingText: "",
							spinnerMode: "thinking",
							vendorStatusText:
								state.streaming.vendorStatusSource === "vendor"
									? state.streaming.vendorStatusText
									: formatVendorStatusLabel(buildFallbackVendorStatus("thinking")),
							vendorStatusSource:
								state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
						},
					}));
				} else if (blockType === "redacted_thinking") {
					addItem({
						kind: "thinking",
						id: uid(),
						data: { text: "", isStreaming: false, isRedacted: true },
					});
				} else if (blockType === "text") {
					set((state) => ({
						streaming: {
							...state.streaming,
							isStreaming: true,
							spinnerMode: "responding",
							vendorStatusText:
								state.streaming.vendorStatusSource === "vendor"
									? state.streaming.vendorStatusText
									: formatVendorStatusLabel(buildFallbackVendorStatus("responding")),
							vendorStatusSource:
								state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
						},
					}));
				} else if (blockType === "tool_use") {
					const toolUseId = String(block.id || uid());
					const toolName = String(block.name || "");
					const tu: StreamingToolUse = {
						toolUseId,
						toolName,
						inputSummary: "",
						rawInput: {},
						status: "streaming-input",
					};
					set((state) => {
						const next = new Map(state.streaming.toolUses);
						next.set(toolUseId, tu);
						return {
							streaming: {
								...state.streaming,
								toolUses: next,
								spinnerMode: "tool-input",
								vendorStatusText:
									state.streaming.vendorStatusSource === "vendor"
										? state.streaming.vendorStatusText
										: formatVendorStatusLabel(buildFallbackVendorStatus("tool-input")),
								vendorStatusSource:
									state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
							},
						};
					});
				}
				return;
			}

			if (evType === "content_block_delta") {
				const delta = event.delta as Record<string, unknown> | undefined;
				if (!delta) return;
				const deltaType = String(delta.type || "");

				if (deltaType === "thinking_delta") {
					const text = String(delta.thinking || "");
					set((state) => ({
						streaming: { ...state.streaming, thinkingText: state.streaming.thinkingText + text },
					}));
				} else if (deltaType === "text_delta") {
					const text = String(delta.text || "");
					set((state) => ({
						streaming: { ...state.streaming, assistantText: state.streaming.assistantText + text },
					}));
				}
				return;
			}

			if (evType === "content_block_stop") {
				const s = get().streaming;
				if (s.isThinking && s.thinkingText) {
					addItem({
						kind: "thinking",
						id: uid(),
						data: { text: s.thinkingText, isStreaming: false, isRedacted: false },
					});
					set((state) => ({
						streaming: { ...state.streaming, isThinking: false, thinkingText: "" },
					}));
				}
				return;
			}

			if (evType === "message_start") {
				set((state) => ({
					streaming: {
						...state.streaming,
						spinnerMode: "requesting",
						vendorStatusText:
							state.streaming.vendorStatusSource === "vendor"
								? state.streaming.vendorStatusText
								: formatVendorStatusLabel(buildFallbackVendorStatus("requesting")),
						vendorStatusSource:
							state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
					},
				}));
			}

			if (evType === "message_delta") {
				set((state) => ({
					streaming: {
						...state.streaming,
						spinnerMode: "responding",
						vendorStatusText:
							state.streaming.vendorStatusSource === "vendor"
								? state.streaming.vendorStatusText
								: formatVendorStatusLabel(buildFallbackVendorStatus("responding")),
						vendorStatusSource:
							state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
					},
				}));
			}
			return;
		}

		// ── tool_progress ─────────────────────────────────────────────────────
		if (type === "tool_progress") {
			const toolUseId = String(msg.tool_use_id || "");
			const elapsed = Number(msg.elapsed_time_seconds ?? 0);
			set((state) => {
				if (!state.streaming.toolUses.has(toolUseId)) return state;
				const next = new Map(state.streaming.toolUses);
				const existing = next.get(toolUseId);
				if (existing) {
					next.set(toolUseId, { ...existing, elapsedSeconds: elapsed, status: "executing" });
				}
				return {
					streaming: {
						...state.streaming,
						toolUses: next,
						spinnerMode: "tool-use",
						vendorStatusText:
							state.streaming.vendorStatusSource === "vendor"
								? state.streaming.vendorStatusText
								: formatVendorStatusLabel(buildFallbackVendorStatus("tool-use")),
						vendorStatusSource:
							state.streaming.vendorStatusSource === "vendor" ? "vendor" : "fallback",
					},
				};
			});
			return;
		}

		// ── result (turn complete) ─────────────────────────────────────────────
		if (type === "result") {
			const isError = Boolean(msg.is_error);
			const numTurns = Number(msg.num_turns ?? 0);
			const totalCostUsd = Number(msg.total_cost_usd ?? 0);
			const durationMs = Number(msg.duration_ms ?? 0);
			addItem({ kind: "result", id: uid(), isError, numTurns, totalCostUsd, durationMs });
			set({ sessionState: "idle", streaming: initialStreaming(), lastUpdatedAt: Date.now() });
			return;
		}

		// ── rate_limit_event ──────────────────────────────────────────────────
		if (type === "rate_limit_event") {
			const info = msg.rate_limit_info as Record<string, unknown> | undefined;
			const status = String(info?.status ?? "allowed");
			const resetsAt = typeof info?.resetsAt === "number" ? info.resetsAt : null;
			const utilization = typeof info?.utilization === "number" ? info.utilization : null;
			set({ rateLimitInfo: { status, resetsAt: resetsAt ?? undefined, utilization: utilization ?? undefined } });
			if (status === "rejected" || status === "allowed_warning") {
				addItem({
					kind: "rate-limit",
					id: uid(),
					resetsAt,
					utilization,
					status,
				});
			}
			return;
		}

		// ── auth_status ───────────────────────────────────────────────────────
		if (type === "auth_status") {
			const output = Array.isArray(msg.output) ? (msg.output as string[]).join("\n") : "";
			if (output) {
				addItem({ kind: "system-notice", id: uid(), text: output, variant: "info" });
			}
			return;
		}

		// ── user (tool_result or first user message) ──────────────────────────
		if (type === "user") {
			const message = msg.message as Record<string, unknown> | undefined;
			const content = message?.content;
			// Capture session title from the first plain text user message
			if (!get().sessionTitle && typeof content === "string" && content.trim()) {
				const title = content.trim().slice(0, 20);
				set({ sessionTitle: title });
			} else if (!get().sessionTitle && Array.isArray(content)) {
				const textBlock = (content as Array<Record<string, unknown>>).find(
					(b) => b.type === "text" && typeof b.text === "string" && (b.text as string).trim(),
				);
				if (textBlock) {
					const title = (textBlock.text as string).trim().slice(0, 20);
					set({ sessionTitle: title });
				}
			}
			
			// Also add the user message to the timeline if it is not just meta/tool_result
			if (!msg.isMeta) {
				const userText = extractTextContent(content);
				if (userText.trim()) {
					// Check if we already optimistically added this message
					const existingUserMsgs = get().items.filter(i => i.kind === "user");
					const lastUserMsg = existingUserMsgs[existingUserMsgs.length - 1];
					if (!lastUserMsg || lastUserMsg.text !== userText.trim()) {
						addItem({ kind: "user", id: String(msg.uuid || uid()), text: userText.trim() });
					}
				}
			}

			if (Array.isArray(content)) {
				for (const block of content as Array<Record<string, unknown>>) {
					if (block.type === "tool_result") {
						const toolUseId = String(block.tool_use_id || "");
						const resultText = extractTextContent(block.content);
						// Update the completed tool-use item in the timeline with result info
						set((state) => ({
							items: state.items.map((item) =>
								item.kind === "tool-use" && item.tool.toolUseId === toolUseId
									? {
											...item,
											tool: {
												...item.tool,
												status: "completed" as const,
												resultSummary: resultText.slice(0, 120),
											},
										}
									: item,
							),
						}));
					}
				}
			}
			return;
		}
	},
}));
